# Generated by Django 5.0.6 on 2024-07-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_amount_pay_order_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ShippingAddress',
            new_name='Shipping_address',
        ),
    ]
